# Generated by Django 4.1 on 2022-11-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now=True)),
                ('rank', models.IntegerField(default=1)),
                ('point', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
