# Generated by Django 4.1 on 2022-11-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theaters', '0001_initial'),
        ('movies', '0001_initial'),
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtimes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinemas')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theaters')),
            ],
            options={
                'db_table': 'movie_showtimes',
            },
        ),
    ]
