# Generated by Django 4.1 on 2022-11-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('poster_url', models.TextField()),
                ('running_time', models.IntegerField(default=0)),
                ('age_rating', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'movie_moives',
            },
        ),
    ]
